enum Screen {
  add('/'),
  get('/get');

  final String path;
  const Screen(this.path);
}

enum Book {
  gen('Genèse', 'GEN'),
  ex('Exode', 'EXO'),
  lev('Lévitique', 'LEV'),
  nom('Nombres', 'NUM'),
  deut('Deutéronome', 'DEU'),
  jos('Josué', 'JOS'),
  jug('Juges', 'JDG'),
  ruth('Ruth', 'RUT'),
  sam1('1 Samuel', '1SA'),
  sam2('2 Samuel', '2SA'),
  roi1('1 Rois', '1KI'),
  roi2('2 Rois', '2KI'),
  chr1('1 Chroniques', '1CH'),
  chr2('2 Chroniques', '2CH'),
  esd('Esdras', 'EZR'),
  neh('Néhémie', 'NEH'),
  est('Esther', 'EST'),
  job('Job', 'JOB'),
  ps('Psaumes', 'PSA'),
  prov('Proverbes', 'PRO'),
  eccl('Ecclésiaste', 'ECC'),
  cant('Cantique', 'CAN'),
  es('Ésaïe', 'ISA'),
  jer('Jérémie', 'JER'),
  lam('Lamentations', 'LAM'),
  eze('Ézékiel', 'EZK'),
  dan('Daniel', 'DAN'),
  os('Osée', 'HOS'),
  joel('Joël', 'JOL'),
  am('Amos', 'AMO'),
  abd('Abdias', 'OBA'),
  jon('Jonas', 'JON'),
  mich('Michée', 'MIC'),
  nah('Nahum', 'NAM'),
  hab('Habacuc', 'HAB'),
  soph('Sophonie', 'ZEP'),
  ag('Aggée', 'HAG'),
  zach('Zacharie', 'ZEC'),
  mal('Malachie', 'MAL'),
  mat('Matthieu', 'MAT'),
  mc('Marc', 'MRK'),
  lc('Luc', 'LUK'),
  jn('Jean', 'JHN'),
  act('Actes', 'ACT'),
  rom('Romains', 'ROM'),
  cor1('1 Corinthiens', '1CO'),
  cor2('2 Corinthiens', '2CO'),
  gal('Galates', 'GAL'),
  eph('Éphésiens', 'EPH'),
  phi('Philippiens', 'PHP'),
  col('Colossiens', 'COL'),
  thes1('1 Thessaloniciens', '1TH'),
  thes2('2 Thessaloniciens', '2TH'),
  tim1('1 Timothée', '1TI'),
  tim2('2 Timothée', '2TI'),
  ti('Tite', 'TIT'),
  phile('Philémon', 'PHM'),
  heb('Hébreux', 'HEB'),
  jacq('Jacques', 'JAS'),
  pier1('1 Pierre', '1PE'),
  pier2('2 Pierre', '2PE'),
  jn1('1 Jean', '1JN'),
  jn2('2 Jean', '2JN'),
  jn3('3 Jean', '3JN'),
  jud('Jude', 'JUD'),
  ap('Apocalypse', 'REV');

  final String label;
  final String suffix;
  const Book(this.label, this.suffix);
}
