enum Screen {
  add('/'),
  get('/get');

  final String path;
  const Screen(this.path);
}

enum Book {
  gen('Genèse'),
  ex('Exode'),
  lev('Lévitique'),
  nom('Nombres'),
  deut('Deutéronome'),
  jos('Josué'),
  jug('Juges'),
  ruth('Ruth'),
  sam1('1 Samuel'),
  sam2('2 Samuel'),
  roi1('1 Rois'),
  roi2('2 Rois'),
  chr1('1 Chroniques'),
  chr2('2 Chroniques'),
  esd('Esdras'),
  neh('Néhémie'),
  est('Esther'),
  job('Job'),
  ps('Psaumes'),
  prov('Proverbes'),
  eccl('Ecclésiaste'),
  cant('Cantique'),
  es('Ésaïe'),
  jer('Jérémie'),
  lam('Lamentations'),
  eze('Ézékiel'),
  dan('Daniel'),
  os('Osée'),
  joel('Joël'),
  am('Amos'),
  abd('Abdias'),
  jon('Jonas'),
  mich('Michée'),
  nah('Nahum'),
  hab('Habacuc'),
  soph('Sophonie'),
  ag('Aggée'),
  zach('Zacharie'),
  mal('Malachie'),
  mat('Matthieu'),
  mc('Marc'),
  lc('Luc'),
  jn('Jean'),
  act('Actes'),
  rom('Romains'),
  cor1('1 Corinthiens'),
  cor2('2 Corinthiens'),
  gal('Galates'),
  eph('Éphésiens'),
  phi('Philippiens'),
  col('Colossiens'),
  thes1('1 Thessaloniciens'),
  thes2('2 Thessaloniciens'),
  tim1('1 Timothée'),
  tim2('2 Timothée'),
  ti('Tite'),
  phile('Philémon'),
  heb('Hébreux'),
  jacq('Jacques'),
  pier1('1 Pierre'),
  pier2('2 Pierre'),
  jn1('1 Jean'),
  jn2('2 Jean'),
  jn3('3 Jean'),
  jud('Jude'),
  ap('Apocalypse');

  final String label;
  const Book(this.label);
}
